# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_gocardless', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirectflow',
            name='completion_redirect_url',
            field=models.URLField(help_text='After completion of the RedirectFlow where to redirect the user to.', null=True),
        ),
        migrations.AlterField(
            model_name='redirectflow',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='The URL of the hosted payment pages for this redirect flow. This is the URL you should redirect your customer to.'),
        ),
    ]
