# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-01 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_gocardless', '0003_no_decimalfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_line1',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_line2',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_line3',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, help_text='Required unless family_name and given_name are provided.', max_length=191),
        ),
        migrations.AlterField(
            model_name='customer',
            name='family_name',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='customer',
            name='swedish_identity_number',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='customerbankaccount',
            name='bank_name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='customerbankaccount',
            name='id',
            field=models.CharField(max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='id',
            field=models.CharField(blank=True, max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='reference',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='scheme',
            field=models.CharField(blank=True, choices=[('autogiro', 'Autogiro'), ('bacs', 'Bacs'), ('sepa_core', 'Sepa Core'), ('sepa_cor1', 'Sepa Cor1')], max_length=191),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='status',
            field=models.CharField(choices=[('pending_submission', 'Pending submission'), ('submitted', 'Submitted'), ('active', 'Active'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending_submission', max_length=191),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='access_token',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='organisation_id',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.CharField(max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending_submission', 'Pending submission'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('charged_back', 'Charged back'), ('paid_out', 'Paid out'), ('cancelled', 'Cancelled'), ('pending_customer_approval', 'Pending customer approval'), ('customer_approval_denied', 'Customer approval denied')], default='pending_submission', max_length=191),
        ),
        migrations.AlterField(
            model_name='payout',
            name='id',
            field=models.CharField(max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=191),
        ),
        migrations.AlterField(
            model_name='redirectflow',
            name='id',
            field=models.CharField(max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='redirectflow',
            name='scheme',
            field=models.CharField(blank=True, choices=[('autogiro', 'Autogiro'), ('bacs', 'Bacs'), ('sepa_core', 'Sepa Core'), ('sepa_cor1', 'Sepa Cor1')], max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='redirectflow',
            name='session_token',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='refund',
            name='id',
            field=models.CharField(max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.CharField(max_length=191, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='interval_unit',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=191),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='month',
            field=models.CharField(blank=True, choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=191),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending_customer_approval', 'Pending customer approval'), ('customer_approval_denied', 'Customer approval denied'), ('active', 'Active'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='pending_customer_approval', max_length=191),
        ),
    ]
