# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-04 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.CharField(max_length=24, unique=True)),
                ('access_token', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'merchants',
                'verbose_name': 'merchant',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.CharField(max_length=24, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('EUR', 'EUR')], default='EUR', max_length=3)),
                ('status', models.CharField(blank=True, choices=[('TIMEDOUT', 'Timed out'), ('CANCELED', 'Cancelled'), ('FAILED', 'Failed'), ('SUCCEEDED', 'Succeeded')], max_length=9, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payconiq.Merchant')),
            ],
            options={
                'verbose_name_plural': 'transactions',
                'verbose_name': 'transaction',
            },
        ),
    ]
