# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-01 23:46
from __future__ import unicode_literals

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import payconiq.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.CharField(help_text='ID in Payconiq systeem.', max_length=24, unique=True, verbose_name='payconiq id')),
                ('access_token', models.TextField(help_text='Toegangstoken.', verbose_name='toegangstoken')),
            ],
            options={
                'verbose_name_plural': 'handelaars',
                'verbose_name': 'handelaar',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_id', models.CharField(help_text='ID in Payconiq systeem.', max_length=24, unique=True, verbose_name='payconiq id')),
                ('amount', models.PositiveIntegerField(help_text='Bedrag in centen.', verbose_name='bedrag')),
                ('currency', models.CharField(choices=[('EUR', 'EUR')], default='EUR', help_text='Valuta.', max_length=3, verbose_name='valuta')),
                ('status', payconiq.fields.StatusSignalCharField(choices=[('UNKNOWN', 'Onbekend'), ('TIMEDOUT', 'Verlopen'), ('CANCELED', 'Geannuleerd'), ('FAILED', 'Gefaald'), ('SUCCEEDED', 'Succesvol')], default='UNKNOWN', help_text='Status.', max_length=9, verbose_name='status')),
                ('merchant', models.ForeignKey(help_text='Handelaar.', on_delete=django.db.models.deletion.CASCADE, to='payconiq.Merchant', verbose_name='handelaar')),
            ],
            options={
                'verbose_name_plural': 'transacties',
                'verbose_name': 'transactie',
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
    ]
