# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-16 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payconiq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchant',
            options={'verbose_name': 'handelaar', 'verbose_name_plural': 'handelaars'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'transactie', 'verbose_name_plural': 'transacties'},
        ),
        migrations.AlterField(
            model_name='merchant',
            name='access_token',
            field=models.TextField(help_text='Toegangstoken.', verbose_name='toegangstoken'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='remote_id',
            field=models.CharField(help_text='ID in Payconiq systeem.', max_length=24, unique=True, verbose_name='payconiq id'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(help_text='Bedrag in centen.', verbose_name='bedrag'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR')], default='EUR', help_text='Valuta.', max_length=3, verbose_name='valuta'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='merchant',
            field=models.ForeignKey(help_text='Handelaar.', on_delete=django.db.models.deletion.CASCADE, to='payconiq.Merchant', verbose_name='handelaar'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='remote_id',
            field=models.CharField(help_text='ID in Payconiq systeem.', max_length=24, unique=True, verbose_name='payconiq id'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('UNKNOWN', 'Onbekend'), ('TIMEDOUT', 'Verlopen'), ('CANCELED', 'Geannuleerd'), ('FAILED', 'Gefaald'), ('SUCCEEDED', 'Succesvol')], default='UNKNOWN', help_text='Status.', max_length=9, verbose_name='status'),
        ),
    ]
