# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-06 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payconiq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('TIMEDOUT', 'Verlopen'), ('CANCELED', 'Geannuleerd'), ('FAILED', 'Gefaald'), ('SUCCEEDED', 'Succesvol')], max_length=9, null=True),
        ),
    ]
