# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-02 19:29
from __future__ import unicode_literals

from django.db import migrations
import payconiq.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payconiq', '0002_auto_20170416_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=payconiq.fields.StatusSignalCharField(choices=[('UNKNOWN', 'Onbekend'), ('TIMEDOUT', 'Verlopen'), ('CANCELED', 'Geannuleerd'), ('FAILED', 'Gefaald'), ('SUCCEEDED', 'Succesvol')], default='UNKNOWN', help_text='Status.', max_length=9, verbose_name='status'),
        ),
    ]
