# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-07 16:43
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payconiq', '0003_auto_20170502_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='name',
            field=models.CharField(
                default=uuid.uuid4,
                help_text='Naam.',
                max_length=191,
                null=True,
                verbose_name='naam'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='widget_token',
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text='Widget token voor web widget gebruik, ook wel online key of secret key genoemd.',
                verbose_name='widget token'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merchant',
            name='access_token',
            field=models.TextField(
                help_text='Geheime toegangstoken voor backend transactions, ook wel access token of auth token genoemd',
                verbose_name='toegangstoken'
            ),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='remote_id',
            field=models.CharField(
                help_text='Merchant ID in Payconiq systeem.',
                max_length=24,
            unique=True,
            verbose_name='payconiq merchant id'
            ),
        ),
    ]
