# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-07 20:57
from __future__ import unicode_literals

import uuid

from django.db import migrations


def generate_name(apps, schema_editor):
    Merchant = apps.get_model('payconiq', 'Merchant')
    for merchant in Merchant.objects.all():
        merchant.name = str(uuid.uuid4())
        merchant.save(
            update_fields=['name']
        )


class Migration(migrations.Migration):

    dependencies = [
        ('payconiq', '0004_widget_token'),
    ]

    operations = [
        migrations.RunPython(
            generate_name,
            reverse_code=migrations.RunPython.noop
        )
    ]
