# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-07 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payconiq', '0005_name_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='name',
            field=models.CharField(
                help_text='Naam.',
                max_length=191,
                unique=True,
                verbose_name='naam'
            ),
            preserve_default=False,
        ),
    ]
