# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-01 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forward',
            name='group',
            field=models.CharField(max_length=191),
        ),
    ]
