# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-21 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('lunch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='store',
            field=models.OneToOneField(blank=True, help_text='Winkel.', null=True, on_delete=django.db.models.deletion.CASCADE, to='lunch.Store', verbose_name='winkel'),
        ),
        migrations.AddField(
            model_name='employeetoken',
            name='employee',
            field=models.ForeignKey(help_text='Werknemer.', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='business.Employee', verbose_name='werknemer'),
        ),
        migrations.AddField(
            model_name='employee',
            name='staff',
            field=models.ForeignKey(help_text='Personeel.', on_delete=django.db.models.deletion.CASCADE, to='business.Staff', verbose_name='personeel'),
        ),
    ]
