# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_staff_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Staff'),
        ),
        migrations.AlterField(
            model_name='stafftoken',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Staff'),
        ),
    ]
