# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20160828_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='password',
        ),
    ]
