# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'werknemer', 'verbose_name_plural': 'weknemers'},
        ),
        migrations.AlterModelOptions(
            name='employeetoken',
            options={'verbose_name': 'werknemerstoken', 'verbose_name_plural': 'werknemerstokens'},
        ),
        migrations.AlterModelOptions(
            name='stafftoken',
            options={'verbose_name': 'personeelstoken', 'verbose_name_plural': 'personeelstokens'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=255, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='owner',
            field=models.BooleanField(default=False, help_text='Of deze werknemer een eigenaar is.', verbose_name='eigenaar'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(help_text='Geëncrypteerd wachtwoord.', max_length=255, verbose_name='wachtwoord'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password_reset',
            field=models.CharField(blank=True, help_text='Code gebruikt om het wachtwoord te veranderen.', max_length=64, verbose_name='wachtwoord reset'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='staff',
            field=models.ForeignKey(help_text='Personeel.', on_delete=django.db.models.deletion.CASCADE, to='business.Staff', verbose_name='peroneel'),
        ),
        migrations.AlterField(
            model_name='employeetoken',
            name='device',
            field=models.CharField(help_text='Naam van het apparaat.', max_length=255, verbose_name='apparaat'),
        ),
        migrations.AlterField(
            model_name='employeetoken',
            name='employee',
            field=models.ForeignKey(help_text='Werknemer.', on_delete=django.db.models.deletion.CASCADE, to='business.Employee', verbose_name='werknemer'),
        ),
        migrations.AlterField(
            model_name='employeetoken',
            name='identifier',
            field=models.CharField(help_text='Idenfitifcatie code die toegang geeft to Lunchbreak.', max_length=255, verbose_name='idenfitifcatie'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(help_text='E-mailadres.', max_length=255, unique=True, verbose_name='e-mailadres'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(help_text='Voornaam.', max_length=255, verbose_name='voornaam'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(help_text='Familienaam.', max_length=255, verbose_name='familienaam'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='merchant',
            field=models.ForeignKey(blank=True, help_text='GoCardless account.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_gocardless.Merchant', verbose_name='GoCardless account'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(help_text='Geëncrypteerd wachtwoord.', max_length=255, verbose_name='wachtwoord'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password_reset',
            field=models.CharField(blank=True, help_text='Code gebruikt om het wachtwoord te veranderen.', max_length=64, verbose_name='wachtwoord reset'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='store',
            field=models.OneToOneField(blank=True, help_text='Winkel.', null=True, on_delete=django.db.models.deletion.CASCADE, to='lunch.Store', verbose_name='winkel'),
        ),
        migrations.AlterField(
            model_name='stafftoken',
            name='device',
            field=models.CharField(help_text='Naam van het apparaat.', max_length=255, verbose_name='apparaat'),
        ),
        migrations.AlterField(
            model_name='stafftoken',
            name='identifier',
            field=models.CharField(help_text='Idenfitifcatie code die toegang geeft to Lunchbreak.', max_length=255, verbose_name='idenfitifcatie'),
        ),
        migrations.AlterField(
            model_name='stafftoken',
            name='staff',
            field=models.ForeignKey(help_text='Personeel.', on_delete=django.db.models.deletion.CASCADE, to='business.Staff', verbose_name='personeel'),
        ),
    ]
