# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-14 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20161024_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'werknemer', 'verbose_name_plural': 'werknemers'},
        ),
    ]
