# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-01 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20161115_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=191, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(help_text='Geëncrypteerd wachtwoord.', max_length=191, verbose_name='wachtwoord'),
        ),
        migrations.AlterField(
            model_name='employeetoken',
            name='device',
            field=models.CharField(help_text='Naam van het apparaat.', max_length=191, verbose_name='apparaat'),
        ),
        migrations.AlterField(
            model_name='employeetoken',
            name='identifier',
            field=models.CharField(help_text='Idenfitifcatie code die toegang geeft to Lunchbreak.', max_length=191, verbose_name='idenfitifcatie'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(help_text='E-mailadres.', max_length=254, unique=True, verbose_name='e-mailadres'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(help_text='Voornaam.', max_length=191, verbose_name='voornaam'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(help_text='Familienaam.', max_length=191, verbose_name='familienaam'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(help_text='Geëncrypteerd wachtwoord.', max_length=191, verbose_name='wachtwoord'),
        ),
        migrations.AlterField(
            model_name='stafftoken',
            name='device',
            field=models.CharField(help_text='Naam van het apparaat.', max_length=191, verbose_name='apparaat'),
        ),
        migrations.AlterField(
            model_name='stafftoken',
            name='identifier',
            field=models.CharField(help_text='Idenfitifcatie code die toegang geeft to Lunchbreak.', max_length=191, verbose_name='idenfitifcatie'),
        ),
    ]
