# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-05 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_utf8mb4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='staff',
            field=models.ForeignKey(help_text='Personeel.', on_delete=django.db.models.deletion.CASCADE, to='business.Staff', verbose_name='personeel'),
        ),
    ]
