# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-13 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payconiq', '0001_initial'),
        ('business', '0012_auto_20170205_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='payconiq',
            field=models.OneToOneField(blank=True, help_text='Payconiq account.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payconiq.Merchant', verbose_name='Payconiq account'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='merchant',
            field=models.OneToOneField(blank=True, help_text='GoCardless account.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_gocardless.Merchant', verbose_name='GoCardless account'),
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='merchant',
            new_name='gocardless',
        ),
    ]
