# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-05 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_auto_20170205_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='merchant',
        ),
    ]
