# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-05 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payconiq', '0001_initial'),
        ('business', '0013_remove_staff_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='merchant',
            field=models.OneToOneField(blank=True, help_text='Payconiq account.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payconiq.Merchant', verbose_name='Payconiq account'),
        ),
    ]
