- lunchFoodCategoryRead: !include lunch/lunchFoodCategoryRead.schema
- lunchFoodCategoryWrite: !include lunch/lunchFoodCategoryWrite.schema
- lunchFoodTypeRead: !include lunch/lunchFoodTypeRead.schema
- lunchFoodTypeWrite: !include lunch/lunchFoodTypeWrite.schema
- lunchHolidayPeriodRead: !include lunch/lunchHolidayPeriodRead.schema
- lunchHolidayPeriodWrite: !include lunch/lunchHolidayPeriodWrite.schema
- lunchIngredientGroupRead: !include lunch/lunchIngredientGroupRead.schema
- lunchIngredientGroupWrite: !include lunch/lunchIngredientGroupWrite.schema
- lunchMultiFoodRead: !include lunch/lunchMultiFoodRead.schema
- lunchMultiFoodWrite: !include lunch/lunchMultiFoodWrite.schema
- lunchNestedIngredientRead: !include lunch/lunchNestedIngredientRead.schema
- lunchNestedIngredientWrite: !include lunch/lunchNestedIngredientWrite.schema
- lunchOpenRead: !include lunch/lunchOpenRead.schema
- lunchOpenWrite: !include lunch/lunchOpenWrite.schema
- lunchOpeningHoursRead: !include lunch/lunchOpeningHoursRead.schema
- lunchOpeningHoursWrite: !include lunch/lunchOpeningHoursWrite.schema
- lunchQuantityRead: !include lunch/lunchQuantityRead.schema
- lunchQuantityWrite: !include lunch/lunchQuantityWrite.schema
- lunchShortFoodCategoryRead: !include lunch/lunchShortFoodCategoryRead.schema
- lunchShortFoodCategoryWrite: !include lunch/lunchShortFoodCategoryWrite.schema
- lunchShortIngredientRelationRead: !include lunch/lunchShortIngredientRelationRead.schema
- lunchShortIngredientRelationWrite: !include lunch/lunchShortIngredientRelationWrite.schema
- lunchShortQuantityRead: !include lunch/lunchShortQuantityRead.schema
- lunchShortQuantityWrite: !include lunch/lunchShortQuantityWrite.schema
- lunchShortSingleFoodRead: !include lunch/lunchShortSingleFoodRead.schema
- lunchShortSingleFoodWrite: !include lunch/lunchShortSingleFoodWrite.schema
- lunchShortStoreRead: !include lunch/lunchShortStoreRead.schema
- lunchShortStoreWrite: !include lunch/lunchShortStoreWrite.schema
- lunchSingleFoodRead: !include lunch/lunchSingleFoodRead.schema
- lunchSingleFoodWrite: !include lunch/lunchSingleFoodWrite.schema
- lunchStoreCategoryRead: !include lunch/lunchStoreCategoryRead.schema
- lunchStoreCategoryWrite: !include lunch/lunchStoreCategoryWrite.schema
- lunchStoreRead: !include lunch/lunchStoreRead.schema
- lunchStoreWrite: !include lunch/lunchStoreWrite.schema
- customersHolidayPeriodRead: !include customers/customersHolidayPeriodRead.schema
- customersHolidayPeriodWrite: !include customers/customersHolidayPeriodWrite.schema
- customersIngredientGroupRead: !include customers/customersIngredientGroupRead.schema
- customersIngredientGroupWrite: !include customers/customersIngredientGroupWrite.schema
- customersOpeningHoursRead: !include customers/customersOpeningHoursRead.schema
- customersOpeningHoursWrite: !include customers/customersOpeningHoursWrite.schema
- customersOrderRead: !include customers/customersOrderRead.schema
- customersOrderWrite: !include customers/customersOrderWrite.schema
- customersOrderedFoodPriceRead: !include customers/customersOrderedFoodPriceRead.schema
- customersOrderedFoodPriceWrite: !include customers/customersOrderedFoodPriceWrite.schema
- customersOrderedFoodRead: !include customers/customersOrderedFoodRead.schema
- customersOrderedFoodWrite: !include customers/customersOrderedFoodWrite.schema
- customersShortOrderRead: !include customers/customersShortOrderRead.schema
- customersShortOrderWrite: !include customers/customersShortOrderWrite.schema
- customersStoreHeartRead: !include customers/customersStoreHeartRead.schema
- customersStoreHeartWrite: !include customers/customersStoreHeartWrite.schema
- customersStoreRead: !include customers/customersStoreRead.schema
- customersStoreWrite: !include customers/customersStoreWrite.schema
- customersUserRead: !include customers/customersUserRead.schema
- customersUserWrite: !include customers/customersUserWrite.schema
- customersUserTokenRead: !include customers/customersUserTokenRead.schema
- customersUserTokenWrite: !include customers/customersUserTokenWrite.schema
- businessEmployeeRead: !include business/businessEmployeeRead.schema
- businessEmployeeWrite: !include business/businessEmployeeWrite.schema
- businessEmployeeTokenRead: !include business/businessEmployeeTokenRead.schema
- businessEmployeeTokenWrite: !include business/businessEmployeeTokenWrite.schema
- businessIngredientGroupRead: !include business/businessIngredientGroupRead.schema
- businessIngredientGroupWrite: !include business/businessIngredientGroupWrite.schema
- businessIngredientRelationRead: !include business/businessIngredientRelationRead.schema
- businessIngredientRelationWrite: !include business/businessIngredientRelationWrite.schema
- businessIngredientRead: !include business/businessIngredientRead.schema
- businessIngredientWrite: !include business/businessIngredientWrite.schema
- businessOrderRead: !include business/businessOrderRead.schema
- businessOrderWrite: !include business/businessOrderWrite.schema
- businessOrderedFoodRead: !include business/businessOrderedFoodRead.schema
- businessOrderedFoodWrite: !include business/businessOrderedFoodWrite.schema
- businessPrivateUserRead: !include business/businessPrivateUserRead.schema
- businessPrivateUserWrite: !include business/businessPrivateUserWrite.schema
- businessShortFoodRead: !include business/businessShortFoodRead.schema
- businessShortFoodWrite: !include business/businessShortFoodWrite.schema
- businessShortIngredientGroupRead: !include business/businessShortIngredientGroupRead.schema
- businessShortIngredientGroupWrite: !include business/businessShortIngredientGroupWrite.schema
- businessShortIngredientRelationRead: !include business/businessShortIngredientRelationRead.schema
- businessShortIngredientRelationWrite: !include business/businessShortIngredientRelationWrite.schema
- businessShortOrderRead: !include business/businessShortOrderRead.schema
- businessShortOrderWrite: !include business/businessShortOrderWrite.schema
- businessStaffRead: !include business/businessStaffRead.schema
- businessStaffWrite: !include business/businessStaffWrite.schema
- businessStaffTokenRead: !include business/businessStaffTokenRead.schema
- businessStaffTokenWrite: !include business/businessStaffTokenWrite.schema
- businessStoreRead: !include business/businessStoreRead.schema
- businessStoreWrite: !include business/businessStoreWrite.schema
