# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 17:26
from __future__ import unicode_literals

import dirtyfields.dirtyfields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=20, verbose_name='Postal code')),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('billing', models.IntegerField(choices=[(0, 'Separate'), (1, 'Leader')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Accepted'), (2, 'Ignored')], default=0)),
            ],
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed', models.DateTimeField(auto_now_add=True, verbose_name='Time of placement')),
                ('receipt', models.DateTimeField(null=True, verbose_name='Time of receipt')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Placed'), (1, 'Denied'), (2, 'Received'), (3, 'Started'), (4, 'Waiting'), (5, 'Completed'), (6, 'Not collected')], default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_confirmed', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True)),
                ('description', models.TextField(blank=True)),
                ('payment_method', models.IntegerField(choices=[(0, 'Cash'), (1, 'GoCardless')], default=0)),
            ],
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.CreateModel(
            name='OrderedFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, default=1, max_digits=7)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_original', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Ordered food',
            },
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('placed', models.DateTimeField(auto_now_add=True, verbose_name='Time of placement')),
                ('reservation_time', models.DateTimeField(verbose_name='Time of reservation')),
                ('comment', models.TextField(blank=True, verbose_name='Comment from user')),
                ('suggestion', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True, verbose_name='Response from store')),
                ('status', models.IntegerField(choices=[(0, 'Placed'), (1, 'Denied'), (2, 'Accepted'), (3, 'Cancelled'), (4, 'Completed'), (5, 'No show')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('digits_id', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Digits ID')),
                ('request_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='Digits Request ID')),
                ('confirmed_at', models.DateField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.IntegerField(choices=[(0, 'GCM'), (1, 'APNS'), (2, 'Inactive')], default=2, verbose_name='Notification service')),
                ('registration_id', models.TextField(blank=True, verbose_name='Registration ID')),
                ('device', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.User')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
    ]
