# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lunch', '0001_initial'),
        ('django_gocardless', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paymentlinks',
            field=models.ManyToManyField(blank=True, through='customers.PaymentLink', to='lunch.Store'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch.Store'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.User'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='redirectflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_gocardless.RedirectFlow'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch.Store'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.User'),
        ),
        migrations.AddField(
            model_name='orderedfood',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='lunch.Ingredient'),
        ),
        migrations.AddField(
            model_name='orderedfood',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Order'),
        ),
        migrations.AddField(
            model_name='orderedfood',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch.Food'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_gocardless.Payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Reservation'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch.Store'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.User'),
        ),
        migrations.AddField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Group'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.User'),
        ),
        migrations.AddField(
            model_name='invite',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Group'),
        ),
        migrations.AddField(
            model_name='invite',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='customers.User'),
        ),
        migrations.AddField(
            model_name='invite',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Membership'),
        ),
        migrations.AddField(
            model_name='invite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.User'),
        ),
        migrations.AddField(
            model_name='heart',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch.Store'),
        ),
        migrations.AddField(
            model_name='heart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(through='customers.Membership', to='customers.User'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.User'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentlink',
            unique_together=set([('user', 'store')]),
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together=set([('group', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='heart',
            unique_together=set([('user', 'store')]),
        ),
    ]
