# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-15 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_temporary_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(choices=[(0, 'Cash'), (1, 'Online (veilig via GoCardless)')], default=0),
        ),
    ]
