# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_user_phone_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mailadres'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Naam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='django_sms.Phone'),
            preserve_default=False,
        ),
    ]
