# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20160923_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(help_text='Stad.', max_length=255, verbose_name='Stad'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(help_text='Land.', max_length=255, verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=7, help_text='Breedtegraad.', max_digits=10, verbose_name='Breedtegraad'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=7, help_text='Lengtegraad.', max_digits=10, verbose_name='Lengtegraad'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(help_text='Straatnummer.', max_length=10, verbose_name='Straatnummer'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(help_text='Postcode.', max_length=20, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(help_text='Provincie.', max_length=255, verbose_name='Provincie'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(help_text='Straat.', max_length=255, verbose_name='Straat'),
        ),
    ]
