# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 20:26
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_address_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'adres', 'verbose_name_plural': 'adressen'},
        ),
        migrations.AlterModelOptions(
            name='heart',
            options={'verbose_name': 'hart', 'verbose_name_plural': 'hartjes'},
        ),
        migrations.AlterModelOptions(
            name='invite',
            options={'verbose_name': 'uitnodiging', 'verbose_name_plural': 'uitnodigingen'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'lidmaatschap', 'verbose_name_plural': 'lidmaatschappen'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'bestelling', 'verbose_name_plural': 'bestellingen'},
        ),
        migrations.AlterModelOptions(
            name='orderedfood',
            options={'verbose_name': 'besteld etenswaar', 'verbose_name_plural': 'bestelde etenswaren'},
        ),
        migrations.AlterModelOptions(
            name='paymentlink',
            options={'verbose_name': 'betalingskoppeling', 'verbose_name_plural': 'betalingskoppelingen'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'reservatie', 'verbose_name_plural': 'reservaties'},
        ),
        migrations.AlterModelOptions(
            name='temporaryorder',
            options={'verbose_name': 'tijdelijke bestelling', 'verbose_name_plural': 'tijdelijke bestellingen'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'gebruiker', 'verbose_name_plural': 'gebruikers'},
        ),
        migrations.AlterModelOptions(
            name='usertoken',
            options={'verbose_name': 'gebruikerstoken', 'verbose_name_plural': 'gebruikerstokens'},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(help_text='Stad.', max_length=255, verbose_name='stad'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(help_text='Land.', max_length=255, verbose_name='land'),
        ),
        migrations.AlterField(
            model_name='address',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Duid aan of het item wacht om verwijderd te worden. Het wordt pas verwijderd wanneer er geen actieve bestellingen meer zijn met dit adres.', verbose_name='verwijderd'),
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=7, help_text='Breedtegraad.', max_digits=10, verbose_name='breedtegraad'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=7, help_text='Lengtegraad.', max_digits=10, verbose_name='lengtegraad'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(help_text='Straatnummer.', max_length=10, verbose_name='straatnummer'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(help_text='Postcode.', max_length=20, verbose_name='postcode'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(help_text='Provincie.', max_length=255, verbose_name='provincie'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(help_text='Straat.', max_length=255, verbose_name='straat'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(help_text='Gebruiker.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='gebruiker'),
        ),
        migrations.AlterField(
            model_name='group',
            name='billing',
            field=models.IntegerField(choices=[(0, 'Iedereen apart'), (1, 'Leider betaalt')], default=0, help_text='Wijze van betaling.', verbose_name='betalingswijze'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=255, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(help_text='Leden.', through='customers.Membership', to=settings.AUTH_USER_MODEL, verbose_name='leden'),
        ),
        migrations.AlterField(
            model_name='heart',
            name='added',
            field=models.DateTimeField(auto_now_add=True, help_text='Datum waarop deze persoon deze winkel "geheart" heeft.', verbose_name='toegevoegd'),
        ),
        migrations.AlterField(
            model_name='heart',
            name='store',
            field=models.ForeignKey(help_text='Winkel.', on_delete=django.db.models.deletion.CASCADE, to='lunch.Store', verbose_name='winkel'),
        ),
        migrations.AlterField(
            model_name='heart',
            name='user',
            field=models.ForeignKey(help_text='Gebruiker.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='gebruiker'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='group',
            field=models.ForeignKey(help_text='Groep.', on_delete=django.db.models.deletion.CASCADE, to='customers.Group', verbose_name='groep'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='invited_by',
            field=models.ForeignKey(help_text='Gebruiker die de uitnodiging heeft verstuurd.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL, verbose_name='uitgenodigd door'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='membership',
            field=models.ForeignKey(blank=True, help_text='Lidmaatschap.', null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Membership', verbose_name='lidmaatschap'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.IntegerField(choices=[(0, 'Wacht op antwoord'), (1, 'Aanvaard'), (2, 'Genegeerd')], default=0, help_text='Status.', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='user',
            field=models.ForeignKey(help_text='Gebruiker.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='gebruiker'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(help_text='Groep.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='customers.Group', verbose_name='groep'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='leader',
            field=models.BooleanField(default=False, help_text='Of dit de leider van de groep is.', verbose_name='leider'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(help_text='Gebruiker.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='gebruiker'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, help_text='Leveringsadres.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Address', verbose_name='leveringsadres'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, help_text='Commentaar.', verbose_name='commentaar'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Betaling.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_gocardless.Payment', verbose_name='betaling'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(choices=[(0, 'Cash'), (1, 'Online (veilig via GoCardless)')], default=0, help_text='Betalingswijze.', verbose_name='betalingswijze'),
        ),
        migrations.AlterField(
            model_name='order',
            name='placed',
            field=models.DateTimeField(auto_now_add=True, help_text='Tijdstip waarop de bestelling werd geplaatst.', verbose_name='tijd van plaatsing'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receipt',
            field=models.DateTimeField(help_text='Tijd van afhalen of levering.', null=True, verbose_name='tijd afgave'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reservation',
            field=models.OneToOneField(blank=True, help_text='Reservaties kunnen gekoppeld worden met een bestelling zodat men kan de bestelling bij de winkel kunnen opeten.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Reservation', verbose_name='reservatie'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Geplaatst'), (1, 'Afgewezen'), (2, 'Ontvangen'), (3, 'Aan begonnen'), (4, 'Ligt klaar'), (5, 'Voltooid'), (6, 'Niet opgehaald')], default=0, help_text='Status.', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='store',
            field=models.ForeignKey(help_text='Winkel.', on_delete=django.db.models.deletion.CASCADE, to='lunch.Store', verbose_name='winkel'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Totale prijs.', max_digits=7, verbose_name='totale prijs'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_confirmed',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Totale prijs na correctie van de winkel indien een afgewogen hoeveelheid licht afwijkt van de bestelde hoeveelheid.', max_digits=7, null=True, verbose_name='totale gecorrigeerde prijs'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='Gebruiker.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='gebruiker'),
        ),
        migrations.AlterField(
            model_name='orderedfood',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Hoeveelheid.', max_digits=7, verbose_name='hoeveelheid'),
        ),
        migrations.AlterField(
            model_name='orderedfood',
            name='comment',
            field=models.TextField(blank=True, help_text='Commentaar.', verbose_name='commentaar'),
        ),
        migrations.AlterField(
            model_name='orderedfood',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Kostprijs.', max_digits=7, verbose_name='kostprijs'),
        ),
        migrations.AlterField(
            model_name='orderedfood',
            name='ingredients',
            field=models.ManyToManyField(blank=True, help_text='Ingrediënten.', to='lunch.Ingredient', verbose_name='ingrediënten'),
        ),
        migrations.AlterField(
            model_name='orderedfood',
            name='is_original',
            field=models.BooleanField(default=False, help_text='Bestelde etenswaren zijn identiek aan het origineel als er geen ingrediënten toegevoegd of afgetrokken werden.', verbose_name='identiek aan origineel'),
        ),
        migrations.AlterField(
            model_name='orderedfood',
            name='original',
            field=models.ForeignKey(help_text='Origineel etenswaar.', on_delete=django.db.models.deletion.CASCADE, to='lunch.Food', verbose_name='origineel etenswaar'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='redirectflow',
            field=models.ForeignKey(help_text='GoCardless doorverwijzing voor het tekenen van een mandaat.', on_delete=django.db.models.deletion.CASCADE, to='django_gocardless.RedirectFlow', verbose_name='doorverwijzing'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='store',
            field=models.ForeignKey(help_text='Winkel.', on_delete=django.db.models.deletion.CASCADE, to='lunch.Store', verbose_name='winkel'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='user',
            field=models.ForeignKey(help_text='Gebruiker.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='gebruiker'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='comment',
            field=models.TextField(blank=True, help_text='Commentaar.', verbose_name='commentaar'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='placed',
            field=models.DateTimeField(auto_now_add=True, help_text='Tijd waarop reservatie werd geplaatst.', verbose_name='geplaatst'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.DateTimeField(help_text='Tijd van reservatie.', verbose_name='tijd van reservatie'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='response',
            field=models.TextField(blank=True, help_text='Antwoord van de winkel.', verbose_name='antwoord'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seats',
            field=models.PositiveIntegerField(default=1, help_text='Plaatsen.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='plaatsen'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Geplaatst'), (1, 'Afgewezen'), (2, 'Aanvaard'), (3, 'Geannuleerd'), (4, 'Voltooid'), (5, 'Niet gekomen')], default=0, help_text='Status.', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='store',
            field=models.ForeignKey(help_text='Winkel.', on_delete=django.db.models.deletion.CASCADE, to='lunch.Store', verbose_name='winkel'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='suggestion',
            field=models.DateTimeField(blank=True, help_text='Indien de reservatie werd afgewezen wordt, kan er een andere datum worden voorgesteld.', null=True, verbose_name='suggestie'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(help_text='Gebruiker.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='gebruiker'),
        ),
        migrations.AlterField(
            model_name='temporaryorder',
            name='store',
            field=models.ForeignKey(help_text='Winkel.', on_delete=django.db.models.deletion.CASCADE, to='lunch.Store', verbose_name='winkel'),
        ),
        migrations.AlterField(
            model_name='temporaryorder',
            name='user',
            field=models.ForeignKey(help_text='Gebruiker.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='gebruiker'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='E-mailadres.', max_length=254, null=True, verbose_name='e-mailadres'),
        ),
        migrations.AlterField(
            model_name='user',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Ingeschakeld.', verbose_name='ingeschakeld'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Lunchbreak werknemer, dit geeft toegang tot het controle paneel.', verbose_name='Lunchbreak werknemer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=255, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='paymentlinks',
            field=models.ManyToManyField(blank=True, help_text='Getekende mandaten.', through='customers.PaymentLink', to='lunch.Store', verbose_name='getekende mandaten'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.OneToOneField(help_text='Telefoonnummer.', on_delete=django.db.models.deletion.CASCADE, to='django_sms.Phone', verbose_name='telefoonnummer'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='device',
            field=models.CharField(help_text='Naam van het apparaat.', max_length=255, verbose_name='apparaat'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='identifier',
            field=models.CharField(help_text='Idenfitifcatie code die toegang geeft to Lunchbreak.', max_length=255, verbose_name='idenfitifcatie'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='user',
            field=models.ForeignKey(help_text='Gebruiker.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='gebruiker'),
        ),
    ]
