# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-01 21:42
from __future__ import unicode_literals

import Lunchbreak.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_auto_20161024_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=Lunchbreak.fields.RoundingDecimalField(decimal_places=7, help_text='Breedtegraad.', max_digits=10, verbose_name='breedtegraad'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=Lunchbreak.fields.RoundingDecimalField(decimal_places=7, help_text='Lengtegraad.', max_digits=10, verbose_name='lengtegraad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=Lunchbreak.fields.RoundingDecimalField(decimal_places=2, default=0, help_text='Totale prijs.', max_digits=7, verbose_name='totale prijs'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_confirmed',
            field=Lunchbreak.fields.RoundingDecimalField(blank=True, decimal_places=2, default=None, help_text='Totale prijs na correctie van de winkel indien een afgewogen hoeveelheid licht afwijkt van de bestelde hoeveelheid.', max_digits=7, null=True, verbose_name='totale gecorrigeerde prijs'),
        ),
        migrations.AlterField(
            model_name='orderedfood',
            name='amount',
            field=Lunchbreak.fields.RoundingDecimalField(decimal_places=3, default=1, help_text='Hoeveelheid.', max_digits=7, verbose_name='hoeveelheid'),
        ),
        migrations.AlterField(
            model_name='orderedfood',
            name='cost',
            field=Lunchbreak.fields.RoundingDecimalField(decimal_places=2, help_text='Kostprijs.', max_digits=7, verbose_name='kostprijs'),
        ),
    ]
