# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-15 00:02
from __future__ import unicode_literals

import Lunchbreak.fields
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0014_ingredientgroup_calc_both'),
        ('customers', '0015_default_rounding'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='invite',
            name='group',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='group',
            name='billing',
        ),
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
        migrations.AddField(
            model_name='group',
            name='deadline',
            field=models.TimeField(default=datetime.time(12, 0), help_text='Deadline voor het plaatsen van bestellingen elke dag.', verbose_name='deadline bestelling'),
        ),
        migrations.AddField(
            model_name='group',
            name='delay',
            field=models.DurationField(default=datetime.timedelta(0, 1800), help_text='Geschatte vertraging na plaatsen bestelling.', verbose_name='geschatte vertraging'),
        ),
        migrations.AddField(
            model_name='group',
            name='discount',
            field=Lunchbreak.fields.RoundingDecimalField(decimal_places=2, default=0, help_text='Korting bij het plaatsen van een bestelling.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='korting'),
        ),
        migrations.AddField(
            model_name='group',
            name='email',
            field=models.EmailField(default='andreas@cloock.be', help_text='E-mailadres gebruikt voor informatie naartoe te sturen.', max_length=254, verbose_name='e-mailadres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='store',
            field=models.ForeignKey(default=1, help_text='Winkel verbonden met deze groep.', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='lunch.Store', verbose_name='winkel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Group waartoe bestelling behoort.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.Group', verbose_name='groep'),
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
