# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-25 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_new_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='store',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='reservation',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
