# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-01 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_removed_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(help_text='Stad.', max_length=191, verbose_name='stad'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(help_text='Land.', max_length=191, verbose_name='land'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(help_text='Provincie.', max_length=191, verbose_name='provincie'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(help_text='Straat.', max_length=191, verbose_name='straat'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=191, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=191, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='device',
            field=models.CharField(help_text='Naam van het apparaat.', max_length=191, verbose_name='apparaat'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='identifier',
            field=models.CharField(help_text='Idenfitifcatie code die toegang geeft to Lunchbreak.', max_length=191, verbose_name='idenfitifcatie'),
        ),
    ]
