# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-08 20:11
from __future__ import unicode_literals

import Lunchbreak.fields
import dirtyfields.dirtyfields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import lunch.config


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_utf8mb4'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Datum van groepsbestelling.', verbose_name='datum')),
                ('status', Lunchbreak.fields.StatusSignalField(choices=[(0, 'Geplaatst'), (1, 'Afgewezen'), (2, 'Ontvangen'), (3, 'Aan begonnen'), (4, 'Ligt klaar'), (5, 'Voltooid'), (6, 'Niet opgehaald')], default=0, help_text='Status.', verbose_name='status')),
            ],
            options={
                'verbose_name_plural': 'groepsbestellingen',
                'verbose_name': 'groepsbestelling',
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'groep', 'verbose_name_plural': 'groepen'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='delivery',
            field=models.BooleanField(default=False, help_text='Bestellingen worden geleverd.', verbose_name='levering'),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Groepsleden.', related_name='store_groups', to=settings.AUTH_USER_MODEL, verbose_name='leden'),
        ),
        migrations.AddField(
            model_name='group',
            name='token',
            field=models.CharField(default=lunch.config.random_token, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=Lunchbreak.fields.RoundingDecimalField(decimal_places=2, default=0, help_text='Korting gegeven op deze bestelling.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='korting'),
        ),
        migrations.AddField(
            model_name='orderedfood',
            name='status',
            field=Lunchbreak.fields.StatusSignalField(choices=[(0, 'Oké'), (1, 'Uit voorraad')], default=0, help_text='Status.', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receipt',
            field=models.DateTimeField(blank=True, help_text='Tijd van afhalen of levering.', null=True, verbose_name='tijd afgave'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=Lunchbreak.fields.StatusSignalField(choices=[(0, 'Geplaatst'), (1, 'Afgewezen'), (2, 'Ontvangen'), (3, 'Aan begonnen'), (4, 'Ligt klaar'), (5, 'Voltooid'), (6, 'Niet opgehaald')], default=0, help_text='Status.', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=Lunchbreak.fields.RoundingDecimalField(decimal_places=2, default=0, help_text='Totale prijs inclusief korting.', max_digits=7, verbose_name='totale prijs'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_confirmed',
            field=Lunchbreak.fields.RoundingDecimalField(blank=True, decimal_places=2, default=None, help_text='Totale prijs na correctie van de winkel indien een afgewogen hoeveelheid licht afwijkt van de bestelde hoeveelheid. Dit is al inclusief het kortingspercentage.', max_digits=7, null=True, verbose_name='totale gecorrigeerde prijs'),
        ),
        migrations.AddField(
            model_name='grouporder',
            name='group',
            field=models.ForeignKey(help_text='Groep.', on_delete=django.db.models.deletion.CASCADE, related_name='group_orders', to='customers.Group', verbose_name='groep'),
        ),
        migrations.AddField(
            model_name='order',
            name='group_order',
            field=models.ForeignKey(blank=True, help_text='Groepsbestelling waartoe bestelling behoort.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.GroupOrder', verbose_name='groepsbestelling'),
        ),
        migrations.AlterUniqueTogether(
            name='grouporder',
            unique_together=set([('group', 'date')]),
        ),
    ]
