# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-26 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_group_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'groep', 'verbose_name_plural': 'groepen'},
        ),
        migrations.AlterField(
            model_name='order',
            name='receipt',
            field=models.DateTimeField(blank=True, help_text='Tijd van afhalen of levering.', null=True, verbose_name='tijd afgave'),
        ),
    ]
