# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-28 13:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import lunch.config


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='token',
            new_name='admin_token',
        ),
        migrations.AddField(
            model_name='group',
            name='join_token',
            field=models.CharField(default=lunch.config.random_token, max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='receipt',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 28, 13, 4, 24, 238893, tzinfo=utc), help_text='Tijd van afhalen of levering.', verbose_name='tijd afgave'),
            preserve_default=False,
        ),
    ]
