# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-21 17:17
from __future__ import unicode_literals

import Lunchbreak.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_grouptokens_receiptnotnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedfood',
            name='total',
            field=Lunchbreak.fields.RoundingDecimalField(decimal_places=2, default=0, help_text='Totale prijs exclusief korting.', max_digits=7, verbose_name='totale prijs'),
        ),
        migrations.AlterField(
            model_name='orderedfood',
            name='original',
            field=models.ForeignKey(blank=True, help_text='Origineel etenswaar.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lunch.Food', verbose_name='origineel etenswaar'),
        ),
    ]
