# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-26 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_auto_20161126_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Datum van groepsbestelling.', verbose_name='datum')),
                ('group', models.ForeignKey(help_text='Groep.', on_delete=django.db.models.deletion.CASCADE, related_name='group_orders', to='customers.Group', verbose_name='groep')),
            ],
            options={
                'verbose_name_plural': 'groepsbestellingen',
                'verbose_name': 'groepsbestelling',
            },
        ),
        migrations.AlterUniqueTogether(
            name='grouporder',
            unique_together=set([('group', 'date')]),
        ),
    ]
