# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-03 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0022_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='delivery',
            field=models.BooleanField(default=False, help_text='Bestellingen worden geleverd.', verbose_name='levering'),
        ),
    ]
