# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-04 01:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import lunch.config


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0023_group_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Groepsleden.', related_name='store_groups', to=settings.AUTH_USER_MODEL, verbose_name='leden'),
        ),
        migrations.AddField(
            model_name='group',
            name='token',
            field=models.CharField(default=lunch.config.random_token, max_length=64),
        ),
    ]
