# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-09 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_confirmed',
        ),
        migrations.RemoveField(
            model_name='orderedfood',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='orderedfood',
            name='total',
        ),
    ]
