# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-09 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_money_old_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_new',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_confirmed_new',
            new_name='total_confirmed',
        ),
        migrations.RenameField(
            model_name='orderedfood',
            old_name='cost_new',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='orderedfood',
            old_name='total_new',
            new_name='total',
        ),
    ]
