# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-04 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0025_order_group_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouporder',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Geplaatst'), (1, 'Afgewezen'), (2, 'Ontvangen'), (3, 'Aan begonnen'), (4, 'Ligt klaar'), (5, 'Voltooid'), (6, 'Niet opgehaald')], default=0, help_text='Status.', verbose_name='status'),
        ),
    ]
