# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-10 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0023_order_placed_default'),
        ('customers', '0025_money_new_renamed'),
    ]

    operations = [
    ]
