# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-10 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payconiq', '0002_auto_20170406_2200'),
        ('customers', '0026_money_new_renamed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentlink',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='paymentlink',
            name='redirectflow',
        ),
        migrations.RemoveField(
            model_name='paymentlink',
            name='store',
        ),
        migrations.RemoveField(
            model_name='paymentlink',
            name='user',
        ),
        migrations.CreateModel(
            name='ConfirmedOrder',
            fields=[
            ],
            options={
                'verbose_name': 'bevestigde bestelling',
                'proxy': True,
                'verbose_name_plural': 'bevestigde bestellingen',
            },
            bases=('customers.order',),
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='paymentlinks',
        ),
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payconiq.Transaction'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(choices=[(0, 'Cash'), (1, 'Online (veilig via Payconiq)')], default=0, help_text='Betalingswijze.', verbose_name='betalingswijze'),
        ),
        migrations.DeleteModel(
            name='PaymentLink',
        ),
    ]
