# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-05 00:26
from __future__ import unicode_literals

import Lunchbreak.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0026_group_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedfood',
            name='status',
            field=Lunchbreak.fields.StatusSignalField(choices=[(0, 'Oké'), (1, 'Uit voorraad')], default=0, help_text='Status.', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='grouporder',
            name='status',
            field=Lunchbreak.fields.StatusSignalField(choices=[(0, 'Geplaatst'), (1, 'Afgewezen'), (2, 'Ontvangen'), (3, 'Aan begonnen'), (4, 'Ligt klaar'), (5, 'Voltooid'), (6, 'Niet opgehaald')], default=0, help_text='Status.', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=Lunchbreak.fields.StatusSignalField(choices=[(0, 'Geplaatst'), (1, 'Afgewezen'), (2, 'Ontvangen'), (3, 'Aan begonnen'), (4, 'Ligt klaar'), (5, 'Voltooid'), (6, 'Niet opgehaald')], default=0, help_text='Status.', verbose_name='status'),
        ),
    ]
