# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-09 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0027_payconiq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(choices=[(0, 'Betalen in winkel'), (1, 'Online (veilig via GoCardless)'), (2, 'Online (veilig via Payconiq)')], default=0, help_text='Betalingswijze.', verbose_name='betalingswijze'),
        ),
    ]
