# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-14 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0028_auto_20170510_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='identifier',
            field=models.CharField(help_text='Identificatie code die toegang geeft tot Lunchbreak.', max_length=191, verbose_name='identificatie'),
        ),
    ]
