# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-01 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Telefoonnummer.', max_length=128, unique=True, verbose_name='telefoonnummer')),
                ('pin', models.CharField(blank=True, help_text='PIN code.', max_length=6, verbose_name='PIN code')),
                ('tries', models.PositiveIntegerField(default=0, help_text='Aantal keer PIN code geprobeerd.', verbose_name='pogingen')),
                ('last_message', models.DateTimeField(blank=True, help_text='Moment waarop het laatste bericht werd verstuurd.', null=True, verbose_name='laatst verstuurd bericht')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Moment waarop er voor het eerste een correcte PIN code werd ingegeven.', null=True, verbose_name='bevestigd op')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Moment waarop PIN code vervalt.', null=True, verbose_name='PIN code vervalt op')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Moment waarop dit telefoonnummer werd toegevoegd.', verbose_name='aangemaakt op')),
            ],
            options={
                'verbose_name_plural': 'telefoons',
                'verbose_name': 'telefoon',
            },
        ),
    ]
