# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-22 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='last_confirmed_message',
            field=models.OneToOneField(blank=True, help_text='Bericht dat laatst bevestigd werd.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_phone', to='django_sms.Message', verbose_name='laatst bevestigd bericht'),
        ),
    ]
