# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-21 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('django_sms', '0002_phone_last_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'telefoon', 'verbose_name_plural': 'telefoons'},
        ),
        migrations.AlterField(
            model_name='phone',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Moment waarop er voor het eerste een correcte PIN code werd ingegeven.', null=True, verbose_name='bevestigd op'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Moment waarop dit telefoonnummer werd toegevoegd.', verbose_name='aangemaakt op'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Moment waarop PIN code vervalt.', null=True, verbose_name='PIN code vervalt op'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='last_message',
            field=models.DateTimeField(blank=True, help_text='Moment waarop het laatste bericht werd verstuurd.', null=True, verbose_name='laatst verstuurd bericht'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Telefoonnummer.', max_length=128, unique=True, verbose_name='telefoonnummer'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='pin',
            field=models.CharField(blank=True, help_text='PIN code.', max_length=6, verbose_name='PIN code'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='tries',
            field=models.PositiveIntegerField(default=0, help_text='Aantal keer PIN code geprobeerd.', verbose_name='pogingen'),
        ),
    ]
