# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-03 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_sms', '0003_auto_20161228_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_uuid', models.UUIDField(null=True)),
                ('gateway', models.CharField(choices=[('plivo', 'Plivo'), ('twilio', 'Twilio')], max_length=6)),
                ('status', models.CharField(choices=[('queued', 'In de wachtrij'), ('sending', 'Wordt verzonden'), ('sent', 'Verzonden'), ('failed', 'Gefaald'), ('delivered', 'Afgeleverd'), ('undelivered', 'Niet afgeleverd'), ('rejected', 'Afgewezen')], default='queued', max_length=11)),
                ('sent_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'bericht',
                'verbose_name_plural': 'berichten',
            },
        ),
        migrations.RemoveField(
            model_name='phone',
            name='last_message',
        ),
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='django_sms.Phone'),
        ),
    ]
