# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-05 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_sms', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='last_confirmed_message',
            field=models.OneToOneField(help_text='Bericht dat laatst bevestigd werd.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_phone', to='django_sms.Message', verbose_name='laatst bevestigd bericht'),
        ),
        migrations.AlterField(
            model_name='message',
            name='error',
            field=models.TextField(blank=True, help_text='Fout informatie.', verbose_name='fout'),
        ),
        migrations.AlterField(
            model_name='message',
            name='gateway',
            field=models.CharField(choices=[('plivo', 'Plivo'), ('twilio', 'Twilio')], help_text='SMS gateway.', max_length=6, verbose_name='gateway'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID.', primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.ForeignKey(help_text='Telefoon.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='django_sms.Phone', verbose_name='telefoon'),
        ),
        migrations.AlterField(
            model_name='message',
            name='remote_uuid',
            field=models.UUIDField(help_text='UUID bij gateway.', null=True, verbose_name='gateway UUID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Verzonden om.', verbose_name='verzonden om'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('queued', 'In de wachtrij'), ('sending', 'Wordt verzonden'), ('sent', 'Verzonden'), ('failed', 'Gefaald'), ('delivered', 'Afgeleverd'), ('undelivered', 'Niet afgeleverd'), ('rejected', 'Afgewezen')], default='queued', help_text='Status.', max_length=11, verbose_name='status'),
        ),
    ]
