# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodCategory',
            new_name='Menu',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='category',
            new_name='menu',
        ),
    ]
