# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0002_foodcategory_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantity',
            old_name='max',
            new_name='maximum',
        ),
        migrations.RenameField(
            model_name='quantity',
            old_name='min',
            new_name='minimum',
        ),
        migrations.AlterField(
            model_name='food',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='lunch.Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='lunch.Store'),
        ),
    ]
