# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 10:38
from __future__ import unicode_literals

import Lunchbreak.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0002_foodtype_store_preorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='ingredientgroups',
            field=models.ManyToManyField(blank=True, help_text='Ingrediëntengroepen.', to='lunch.IngredientGroup', verbose_name='ingrediëntengroepen'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cost',
            field=Lunchbreak.fields.CostField(default=0, help_text='Basisprijs die in rekening wordt gebracht afhankelijk van de prijsberekening ingesteld op de ingrediëntengroep.', verbose_name='basisprijs'),
        ),
    ]
