# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0003_min_max_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='lunch.IngredientGroup'),
        ),
    ]
