# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0005_auto_20160901_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='customisable',
            field=models.BooleanField(default=True),
        ),
    ]
