# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 12:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0006_temporary_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'winkel', 'verbose_name_plural': 'winkels'},
        ),
        migrations.AlterField(
            model_name='store',
            name='categories',
            field=models.ManyToManyField(help_text='Cateogorieën.', to='lunch.StoreCategory', verbose_name='Cateogorieën'),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(help_text='Stad.', max_length=255, verbose_name='Stad'),
        ),
        migrations.AlterField(
            model_name='store',
            name='country',
            field=models.CharField(help_text='Land.', max_length=255, verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='store',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Ingeschakeld.', verbose_name='Ingeschakeld'),
        ),
        migrations.AlterField(
            model_name='store',
            name='header',
            field=models.ForeignKey(blank=True, help_text='Header afbeelding.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lunch.StoreHeader', verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='store',
            name='hearts',
            field=models.ManyToManyField(blank=True, help_text='Hearts van klanten.', through='customers.Heart', to=settings.AUTH_USER_MODEL, verbose_name='Hearts'),
        ),
        migrations.AlterField(
            model_name='store',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='Wanneer deze winkel laatst aangepast werd.', verbose_name='Laatst aangepast'),
        ),
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(decimal_places=7, help_text='Breedtegraad.', max_digits=10, verbose_name='Breedtegraad'),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(decimal_places=7, help_text='Lengtegraad.', max_digits=10, verbose_name='Lengtegraad'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=255, verbose_name='Naam'),
        ),
        migrations.AlterField(
            model_name='store',
            name='number',
            field=models.CharField(help_text='Straatnummer.', max_length=10, verbose_name='Straatnummer'),
        ),
        migrations.AlterField(
            model_name='store',
            name='postcode',
            field=models.CharField(help_text='Postcode.', max_length=20, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='store',
            name='preorder_time',
            field=models.TimeField(default=datetime.time(12, 0), help_text='Indien bepaalde waren meer dan een dag op voorhand besteld moeten worden, moeten ze voor dit tijdstip besteld worden.', verbose_name='Tijd voorafgaande bestelling'),
        ),
        migrations.AlterField(
            model_name='store',
            name='province',
            field=models.CharField(help_text='Provincie.', max_length=255, verbose_name='Provincie'),
        ),
        migrations.AlterField(
            model_name='store',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text="Regio's waaraan geleverd wordt.", to='lunch.Region', verbose_name="Regio's"),
        ),
        migrations.AlterField(
            model_name='store',
            name='seats_max',
            field=models.PositiveIntegerField(default=10, help_text='Maximum aantal plaatsen voor reservaties.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum plaatsen'),
        ),
        migrations.AlterField(
            model_name='store',
            name='street',
            field=models.CharField(help_text='Straat.', max_length=255, verbose_name='Straat'),
        ),
        migrations.AlterField(
            model_name='store',
            name='wait',
            field=models.DurationField(default=datetime.timedelta(0, 60), help_text='Minimum tijd dat op voorhand besteld moet worden.', verbose_name='Wachttijd'),
        ),
    ]
