# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 20:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import private_media.storages


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0007_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryperiod',
            options={'verbose_name': 'leveringstijd', 'verbose_name_plural': 'leveringstijden'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'etenswaar', 'verbose_name_plural': 'etenswaren'},
        ),
        migrations.AlterModelOptions(
            name='foodtype',
            options={'verbose_name': 'type etenswaar', 'verbose_name_plural': 'type etenswaren'},
        ),
        migrations.AlterModelOptions(
            name='holidayperiod',
            options={'verbose_name': 'vakantieperiode', 'verbose_name_plural': 'vakantieperiodes'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'ingrediënt', 'verbose_name_plural': 'ingrediënt'},
        ),
        migrations.AlterModelOptions(
            name='ingredientgroup',
            options={'verbose_name': 'ingrediëntengroep', 'verbose_name_plural': 'ingrediëntengroepen'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'menu', 'verbose_name_plural': "menu's"},
        ),
        migrations.AlterModelOptions(
            name='openingperiod',
            options={'verbose_name': 'openingstijd', 'verbose_name_plural': 'openingstijden'},
        ),
        migrations.AlterModelOptions(
            name='quantity',
            options={'verbose_name': 'hoeveelheid', 'verbose_name_plural': 'hoeveelheden'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'regio', 'verbose_name_plural': "regio's"},
        ),
        migrations.AlterModelOptions(
            name='storecategory',
            options={'verbose_name': 'winkelcategorie', 'verbose_name_plural': 'winkelcategorieën'},
        ),
        migrations.AlterModelOptions(
            name='storeheader',
            options={'verbose_name': 'headerafbeelding', 'verbose_name_plural': 'headerafbeeldingen'},
        ),
        migrations.RemoveField(
            model_name='storecategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='store',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Tijdzone.', max_length=255, verbose_name='tijdzone'),
        ),
        migrations.AlterField(
            model_name='deliveryperiod',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Maandag'), (2, 'Dinsdag'), (3, 'Woensdag'), (4, 'Donderdag'), (5, 'Vrijdag'), (6, 'Zaterdag'), (7, 'Zondag')], help_text='Dag van de week.', verbose_name='weekdag'),
        ),
        migrations.AlterField(
            model_name='deliveryperiod',
            name='duration',
            field=models.DurationField(help_text='Hoelang de winkel open is vanaf de openingstijd.', verbose_name='openingsduur'),
        ),
        migrations.AlterField(
            model_name='deliveryperiod',
            name='store',
            field=models.ForeignKey(help_text='Winkel.', on_delete=django.db.models.deletion.CASCADE, to='lunch.Store', verbose_name='winkel'),
        ),
        migrations.AlterField(
            model_name='deliveryperiod',
            name='time',
            field=models.TimeField(help_text='Tijdstip waarop de winkel opengaat.', verbose_name='openingstijd'),
        ),
        migrations.AlterField(
            model_name='food',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Hoeveelheid die standaard is ingevuld.', max_digits=7, verbose_name='standaardhoeveelheid'),
        ),
        migrations.AlterField(
            model_name='food',
            name='commentable',
            field=models.BooleanField(default=False, help_text='Of er commentaar kan achter worden gelaten bij het bestellen.', verbose_name='commentaar mogelijk'),
        ),
        migrations.AlterField(
            model_name='food',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Basisprijs, dit is inclusief de gekozen ingrediënten en ingrediëntengroepen.', max_digits=7, verbose_name='basisprijs'),
        ),
        migrations.AlterField(
            model_name='food',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Duid aan of het item wacht om verwijderd te worden. Het wordt pas verwijderd wanneer er geen actieve bestellingen meer zijn met dit etenswaar.', verbose_name='verwijderd'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, help_text='Beschrijving.', verbose_name='beschrijving'),
        ),
        migrations.AlterField(
            model_name='food',
            name='foodtype',
            field=models.ForeignKey(help_text='Type etenswaar.', on_delete=django.db.models.deletion.CASCADE, to='lunch.FoodType', verbose_name='type etenswaar'),
        ),
        migrations.AlterField(
            model_name='food',
            name='ingredientgroups',
            field=models.ManyToManyField(blank=True, help_text='Inrgediëntengroep.', to='lunch.IngredientGroup', verbose_name='inrgediëntengroep'),
        ),
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.ManyToManyField(blank=True, help_text='Ingrediënten.', through='lunch.IngredientRelation', to='lunch.Ingredient', verbose_name='ingrediënten'),
        ),
        migrations.AlterField(
            model_name='food',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='Laatst aangepast.', verbose_name='laatst aangepast'),
        ),
        migrations.AlterField(
            model_name='food',
            name='menu',
            field=models.ForeignKey(help_text='Menu.', on_delete=django.db.models.deletion.CASCADE, related_name='food', to='lunch.Menu', verbose_name='menu'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=255, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='food',
            name='preorder_days',
            field=models.PositiveIntegerField(default=0, help_text='Minimum dagen op voorhand bestellen voor het uur ingesteld op de winkel.', verbose_name='dagen op voorhand bestellen'),
        ),
        migrations.AlterField(
            model_name='food',
            name='priority',
            field=models.BigIntegerField(default=0, help_text='Prioriteit.', verbose_name='prioriteit'),
        ),
        migrations.AlterField(
            model_name='food',
            name='store',
            field=models.ForeignKey(help_text='Winkel.', on_delete=django.db.models.deletion.CASCADE, to='lunch.Store', verbose_name='winkel'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='customisable',
            field=models.BooleanField(default=True, help_text='Of dit type etenswaar aanpasbaar kan zijn.', verbose_name='aanpasbaar'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='inputtype',
            field=models.PositiveIntegerField(choices=[(0, 'Aantal'), (1, 'Aanpasbaar o.b.v. SI-eenheid'), (2, 'Vaste hoeveelheid o.b.v. SI-eenheid')], default=0, help_text='Invoer type die aanduid hoe de hoeveelheid ingegeven moet en kan worden.', verbose_name='invoer type'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=255, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='quantifier',
            field=models.CharField(blank=True, help_text='Naam van de eenheid van eten, vb: "broodjes", "broden"...', max_length=255, null=True, verbose_name='eenheid'),
        ),
        migrations.AlterField(
            model_name='holidayperiod',
            name='closed',
            field=models.BooleanField(default=True, help_text='Of de winkel gesloten is tijdens deze vakantieperiode.', verbose_name='gesloten'),
        ),
        migrations.AlterField(
            model_name='holidayperiod',
            name='description',
            field=models.CharField(blank=True, help_text='Beschrijving met een reden.', max_length=255, verbose_name='beschrijving'),
        ),
        migrations.AlterField(
            model_name='holidayperiod',
            name='end',
            field=models.DateTimeField(help_text='Einde van de vakantieperiode.', verbose_name='einde'),
        ),
        migrations.AlterField(
            model_name='holidayperiod',
            name='start',
            field=models.DateTimeField(help_text='Start van de vakantieperiode.', verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='holidayperiod',
            name='store',
            field=models.ForeignKey(help_text='Winkel.', on_delete=django.db.models.deletion.CASCADE, to='lunch.Store', verbose_name='winkel'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Basisprijs diet in rekening wordt gebracht afhankelijk van de prijsberekening ingesteld op de ingrediëntengroep.', max_digits=7, verbose_name='basisprijs'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='group',
            field=models.ForeignKey(help_text='Ingrediëntengroep.', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='lunch.IngredientGroup', verbose_name='ingrediëntengroep'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='Laatst aangepast.', verbose_name='laatst aangepast'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=255, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='store',
            field=models.ForeignKey(help_text='Winkel.', on_delete=django.db.models.deletion.CASCADE, to='lunch.Store', verbose_name='winkel'),
        ),
        migrations.AlterField(
            model_name='ingredientgroup',
            name='calculation',
            field=models.PositiveIntegerField(choices=[(0, 'Altijd de groepsprijs'), (1, 'Duurder bij toevoegen, zelfde bij aftrekken'), (2, 'Duurder bij toevoegen, goedkoper bij aftrekken')], default=0, help_text='Manier waarop de prijs moet berekened worden indien ingrediënten aangepast toegevoegd of afgetrokken worden.', verbose_name='prijsberekening'),
        ),
        migrations.AlterField(
            model_name='ingredientgroup',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Basisprijs indien toegevoegd of afgetrokken van het etenswaar.', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='basisprijs'),
        ),
        migrations.AlterField(
            model_name='ingredientgroup',
            name='foodtype',
            field=models.ForeignKey(help_text='Type etenswaar.', on_delete=django.db.models.deletion.CASCADE, to='lunch.FoodType', verbose_name='type etenswaar'),
        ),
        migrations.AlterField(
            model_name='ingredientgroup',
            name='maximum',
            field=models.PositiveIntegerField(default=0, help_text='Maximum hoeveelheid.', verbose_name='maximum'),
        ),
        migrations.AlterField(
            model_name='ingredientgroup',
            name='minimum',
            field=models.PositiveIntegerField(default=0, help_text='Minimum hoeveelheid.', verbose_name='minimum'),
        ),
        migrations.AlterField(
            model_name='ingredientgroup',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=255, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='ingredientgroup',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Prioriteit waarop gesorteerd wordt.', verbose_name='prioriteit'),
        ),
        migrations.AlterField(
            model_name='ingredientgroup',
            name='store',
            field=models.ForeignKey(help_text='Winkel.', on_delete=django.db.models.deletion.CASCADE, to='lunch.Store', verbose_name='winkel'),
        ),
        migrations.AlterField(
            model_name='ingredientrelation',
            name='food',
            field=models.ForeignKey(help_text='Etenswaar.', on_delete=django.db.models.deletion.CASCADE, to='lunch.Food', verbose_name='etenswaar'),
        ),
        migrations.AlterField(
            model_name='ingredientrelation',
            name='ingredient',
            field=models.ForeignKey(help_text='Ingrediënt.', on_delete=django.db.models.deletion.CASCADE, to='lunch.Ingredient', verbose_name='ingrediënt'),
        ),
        migrations.AlterField(
            model_name='ingredientrelation',
            name='selected',
            field=models.BooleanField(default=False, help_text='Of het ingrediënt standaard geselecteerd is.', verbose_name='geselecteerd'),
        ),
        migrations.AlterField(
            model_name='ingredientrelation',
            name='typical',
            field=models.BooleanField(default=False, help_text='Of het een typisch ingrediënt is voor het gelinkte etenswaar.', verbose_name='typisch'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=255, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Prioriteit.', verbose_name='prioriteit'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='store',
            field=models.ForeignKey(help_text='Winkel.', on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='lunch.Store', verbose_name='winkel'),
        ),
        migrations.AlterField(
            model_name='openingperiod',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Maandag'), (2, 'Dinsdag'), (3, 'Woensdag'), (4, 'Donderdag'), (5, 'Vrijdag'), (6, 'Zaterdag'), (7, 'Zondag')], help_text='Dag van de week.', verbose_name='weekdag'),
        ),
        migrations.AlterField(
            model_name='openingperiod',
            name='duration',
            field=models.DurationField(help_text='Hoelang de winkel open is vanaf de openingstijd.', verbose_name='openingsduur'),
        ),
        migrations.AlterField(
            model_name='openingperiod',
            name='store',
            field=models.ForeignKey(help_text='Winkel.', on_delete=django.db.models.deletion.CASCADE, to='lunch.Store', verbose_name='winkel'),
        ),
        migrations.AlterField(
            model_name='openingperiod',
            name='time',
            field=models.TimeField(help_text='Tijdstip waarop de winkel opengaat.', verbose_name='openingstijd'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='foodtype',
            field=models.ForeignKey(help_text='Type etenswaar.', on_delete=django.db.models.deletion.CASCADE, to='lunch.FoodType', verbose_name='type etenswaar'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='Laatst aangepast.', verbose_name='laatst aangepast'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='maximum',
            field=models.DecimalField(decimal_places=3, default=10, help_text='Maximum hoeveelheid.', max_digits=7, verbose_name='maximum'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='minimum',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Minimum hoeveelheid.', max_digits=7, verbose_name='minimum'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='store',
            field=models.ForeignKey(help_text='Winkel.', on_delete=django.db.models.deletion.CASCADE, to='lunch.Store', verbose_name='winkel'),
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.PositiveSmallIntegerField(choices=[(0, 'België'), (1, 'Nederland'), (2, 'Luxemburg'), (3, 'Frankrijk'), (4, 'Duitsland')], help_text='Land.', verbose_name='land'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=255, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='region',
            name='postcode',
            field=models.CharField(help_text='Postcode.', max_length=255, verbose_name='postcode'),
        ),
        migrations.AlterField(
            model_name='store',
            name='categories',
            field=models.ManyToManyField(help_text='Winkelcategorieën.', to='lunch.StoreCategory', verbose_name='winkelcategorieën'),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(help_text='Stad.', max_length=255, verbose_name='stad'),
        ),
        migrations.AlterField(
            model_name='store',
            name='country',
            field=models.CharField(help_text='Land.', max_length=255, verbose_name='land'),
        ),
        migrations.AlterField(
            model_name='store',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Ingeschakeld.', verbose_name='ingeschakeld'),
        ),
        migrations.AlterField(
            model_name='store',
            name='header',
            field=models.ForeignKey(blank=True, help_text='Header afbeelding.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lunch.StoreHeader', verbose_name='header'),
        ),
        migrations.AlterField(
            model_name='store',
            name='hearts',
            field=models.ManyToManyField(blank=True, help_text='Hartjes van klanten.', through='customers.Heart', to=settings.AUTH_USER_MODEL, verbose_name='hartjes'),
        ),
        migrations.AlterField(
            model_name='store',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='Wanneer deze winkel laatst aangepast werd.', verbose_name='laatst aangepast'),
        ),
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(decimal_places=7, help_text='Breedtegraad.', max_digits=10, verbose_name='breedtegraad'),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(decimal_places=7, help_text='Lengtegraad.', max_digits=10, verbose_name='lengtegraad'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=255, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='store',
            name='number',
            field=models.CharField(help_text='Straatnummer.', max_length=10, verbose_name='straatnummer'),
        ),
        migrations.AlterField(
            model_name='store',
            name='postcode',
            field=models.CharField(help_text='Postcode.', max_length=20, verbose_name='postcode'),
        ),
        migrations.AlterField(
            model_name='store',
            name='preorder_time',
            field=models.TimeField(default=datetime.time(12, 0), help_text='Indien bepaalde waren meer dan een dag op voorhand besteld moeten worden, moeten ze voor dit tijdstip besteld worden.', verbose_name='tijd voorafgaande bestelling'),
        ),
        migrations.AlterField(
            model_name='store',
            name='province',
            field=models.CharField(help_text='Provincie.', max_length=255, verbose_name='provincie'),
        ),
        migrations.AlterField(
            model_name='store',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text="Regio's waaraan geleverd wordt.", to='lunch.Region', verbose_name="regio's"),
        ),
        migrations.AlterField(
            model_name='store',
            name='seats_max',
            field=models.PositiveIntegerField(default=10, help_text='Maximum aantal plaatsen voor reservaties.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='maximum plaatsen'),
        ),
        migrations.AlterField(
            model_name='store',
            name='street',
            field=models.CharField(help_text='Straat.', max_length=255, verbose_name='straat'),
        ),
        migrations.AlterField(
            model_name='store',
            name='wait',
            field=models.DurationField(default=datetime.timedelta(0, 60), help_text='Minimum tijd dat op voorhand besteld moet worden.', verbose_name='wachttijd'),
        ),
        migrations.AlterField(
            model_name='storecategory',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=255, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='storeheader',
            name='original',
            field=models.ImageField(help_text='De originele afbeelding die werd geüpload.', storage=private_media.storages.PrivateMediaStorage(), upload_to='storeheader', verbose_name='origineel'),
        ),
    ]
