# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-16 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0009_storeheader_onetoone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='customisable',
            field=models.BooleanField(default=False, help_text='Of dit type etenswaar aanpasbaar kan zijn.', verbose_name='aanpasbaar'),
        ),
        migrations.AlterField(
            model_name='storeheader',
            name='store',
            field=models.OneToOneField(help_text='Winkel.', on_delete=django.db.models.deletion.CASCADE, related_name='header', to='lunch.Store', verbose_name='winkel'),
        ),
    ]
