# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-24 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0010_foodtype_customisable_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='online_payments_enabled',
            field=models.BooleanField(default=True, help_text='Online betalingen inschakelen, er moet een GoCardless account/merchant gelinked worden voor online betalingen aanvaard kunnen worden.', verbose_name='online betalingen inschakelen'),
        ),
    ]
