# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-31 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0011_store_online_payments_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='online_payments_enabled',
            field=models.BooleanField(default=True, help_text='Online betalingen ingeschakeld, er moet een GoCardless account/merchant gelinked worden voor online betalingen aanvaard kunnen worden.', verbose_name='online betalingen ingeschakeld'),
        ),
    ]
