# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-01 21:42
from __future__ import unicode_literals

import Lunchbreak.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0012_auto_20161031_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='amount',
            field=Lunchbreak.fields.RoundingDecimalField(decimal_places=3, default=1, help_text='Hoeveelheid die standaard is ingevuld.', max_digits=7, verbose_name='standaardhoeveelheid'),
        ),
        migrations.AlterField(
            model_name='food',
            name='cost',
            field=Lunchbreak.fields.RoundingDecimalField(decimal_places=2, help_text='Basisprijs, dit is inclusief de gekozen ingrediënten en ingrediëntengroepen.', max_digits=7, verbose_name='basisprijs'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cost',
            field=Lunchbreak.fields.RoundingDecimalField(decimal_places=2, default=0, help_text='Basisprijs diet in rekening wordt gebracht afhankelijk van de prijsberekening ingesteld op de ingrediëntengroep.', max_digits=7, verbose_name='basisprijs'),
        ),
        migrations.AlterField(
            model_name='ingredientgroup',
            name='cost',
            field=Lunchbreak.fields.RoundingDecimalField(decimal_places=2, default=0, help_text='Basisprijs indien toegevoegd of afgetrokken van het etenswaar.', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='basisprijs'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='maximum',
            field=Lunchbreak.fields.RoundingDecimalField(decimal_places=3, default=10, help_text='Maximum hoeveelheid.', max_digits=7, verbose_name='maximum'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='minimum',
            field=Lunchbreak.fields.RoundingDecimalField(decimal_places=3, default=1, help_text='Minimum hoeveelheid.', max_digits=7, verbose_name='minimum'),
        ),
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=Lunchbreak.fields.RoundingDecimalField(decimal_places=7, help_text='Breedtegraad.', max_digits=10, verbose_name='breedtegraad'),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=Lunchbreak.fields.RoundingDecimalField(decimal_places=7, help_text='Lengtegraad.', max_digits=10, verbose_name='lengtegraad'),
        ),
    ]
