# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-01 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0014_ingredientgroup_calc_both'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=191, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=191, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='quantifier',
            field=models.CharField(blank=True, help_text='Naam van de eenheid van eten, vb: "broodjes", "broden"...', max_length=191, null=True, verbose_name='eenheid'),
        ),
        migrations.AlterField(
            model_name='holidayperiod',
            name='description',
            field=models.CharField(blank=True, help_text='Beschrijving met een reden.', max_length=191, verbose_name='beschrijving'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=191, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='ingredientgroup',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=191, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=191, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=191, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='region',
            name='postcode',
            field=models.CharField(help_text='Postcode.', max_length=191, verbose_name='postcode'),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(help_text='Stad.', max_length=191, verbose_name='stad'),
        ),
        migrations.AlterField(
            model_name='store',
            name='country',
            field=models.CharField(help_text='Land.', max_length=191, verbose_name='land'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=191, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='store',
            name='province',
            field=models.CharField(help_text='Provincie.', max_length=191, verbose_name='provincie'),
        ),
        migrations.AlterField(
            model_name='store',
            name='street',
            field=models.CharField(help_text='Straat.', max_length=191, verbose_name='straat'),
        ),
        migrations.AlterField(
            model_name='store',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Tijdzone.', max_length=191, verbose_name='tijdzone'),
        ),
        migrations.AlterField(
            model_name='storecategory',
            name='name',
            field=models.CharField(help_text='Naam.', max_length=191, verbose_name='naam'),
        ),
    ]
