# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-28 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0016_utf8mb4_encoding_collation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrelation',
            name='food',
            field=models.ForeignKey(help_text='Etenswaar.', on_delete=django.db.models.deletion.CASCADE, related_name='ingredientrelations', to='lunch.Food', verbose_name='etenswaar'),
        ),
        migrations.AlterField(
            model_name='ingredientrelation',
            name='ingredient',
            field=models.ForeignKey(help_text='Ingrediënt.', on_delete=django.db.models.deletion.CASCADE, related_name='ingredientrelations', to='lunch.Ingredient', verbose_name='ingrediënt'),
        ),
    ]
