# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-21 17:27
from __future__ import unicode_literals

import django.db.models.manager
from django.db import migrations, models
from django.utils import timezone


def safedelete_migration(apps, schema_editor, forward):
    Food = apps.get_model('lunch', 'Food')
    if forward:
        Food.manager_superclass.filter(
            old_deleted=True
        ).update(
            deleted=timezone.now()
        )
    else:
        Food.manager_superclass.filter(
            deleted__isnull=False
        ).update(
            old_deleted=True
        )


def safedelete_migration_forward(apps, schema_editor):
    return safedelete_migration(apps, schema_editor, forward=True)


def safedelete_migration_reverse(apps, schema_editor):
    return safedelete_migration(apps, schema_editor, forward=False)


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0017_safedelete'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='food',
            managers=[
                ('manager_superclass', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.RunPython(safedelete_migration_forward, safedelete_migration_reverse),
        migrations.RemoveField(
            model_name='food',
            name='old_deleted',
        ),
    ]
