# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-20 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0017_auto_20161228_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'ingrediënt', 'verbose_name_plural': 'ingrediënten'},
        ),
        migrations.RemoveField(
            model_name='food',
            name='store',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='store',
        ),
    ]
