# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-10 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0020_food_safedelete'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='food',
            managers=[
            ],
        ),
    ]
