# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-09 19:37
from __future__ import unicode_literals

import Lunchbreak.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0021_food_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cost_new',
            field=Lunchbreak.fields.CostField(default=0, help_text='Basisprijs, dit is inclusief de gekozen ingrediënten en ingrediëntengroepen.', verbose_name='basisprijs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cost_new',
            field=Lunchbreak.fields.CostField(default=0, help_text='Basisprijs diet in rekening wordt gebracht afhankelijk van de prijsberekening ingesteld op de ingrediëntengroep.', verbose_name='basisprijs'),
        ),
        migrations.AddField(
            model_name='ingredientgroup',
            name='cost_new',
            field=Lunchbreak.fields.CostField(default=0, help_text='Basisprijs indien toegevoegd of afgetrokken van het etenswaar.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='basisprijs'),
        )
    ]
