# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-09 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0022_money'),
        ('customers', '0023_money')
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='ingredientgroup',
            name='cost',
        )
    ]
