# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-09 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0023_money_old_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='cost_new',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='cost_new',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='ingredientgroup',
            old_name='cost_new',
            new_name='cost',
        )
    ]
