# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-13 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0024_money_new_renamed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='online_payments_enabled',
            new_name='gocardless_enabled',
        ),
        migrations.AlterField(
            model_name='store',
            name='gocardless_enabled',
            field=models.BooleanField(default=True, help_text='Online betalingen ingeschakeld, er moet een GoCardless merchant gelinkt worden voor online betalingen aanvaard kunnen worden.', verbose_name='gocardless betalingen ingeschakeld'),
        ),
        migrations.AddField(
            model_name='store',
            name='payconiq_enabled',
            field=models.BooleanField(default=True, help_text='Online betalingen ingeschakeld, er moet een Payconiq merchant gelinkt worden voor online betalingen aanvaard kunnen worden.', verbose_name='payconiq betalingen ingeschakeld'),
        ),
    ]
