# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-26 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0025_payconiq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='preorder_days',
            field=models.IntegerField(default=-1, help_text='Minimum dagen op voorhand bestellen voor het uur ingesteld op de winkel. (-1 is uitgeschakeld, 0 is dezelfde dag voor het bepaalde uur.)', verbose_name='dagen op voorhand bestellen'),
        ),
    ]
