# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-09 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0026_preorder_days_same_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='gocardless_enabled',
            field=models.BooleanField(default=False, help_text='Online betalingen ingeschakeld, er moet een GoCardless merchant gelinkt worden voor online betalingen aanvaard kunnen worden.', verbose_name='gocardless betalingen ingeschakeld'),
        ),
        migrations.AlterField(
            model_name='store',
            name='payconiq_enabled',
            field=models.BooleanField(default=False, help_text='Online betalingen ingeschakeld, er moet een Payconiq merchant gelinkt worden voor online betalingen aanvaard kunnen worden.', verbose_name='payconiq betalingen ingeschakeld'),
        ),
    ]
