# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-07 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0027_gc_pc_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cash_enabled',
            field=models.BooleanField(default=True, help_text='Betalingen in winkel ingeschakeld.', verbose_name='betalingen in winkel ingeschakeld'),
        ),
    ]
