# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-01 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0027_gc_pc_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='preorder_days',
            field=models.IntegerField(default=0, help_text='Minimum dagen op voorhand bestellen voor het uur ingesteld op de winkel. (0 is uitgeschakeld, >=1 is dezelfde dag voor het bepaalde uur.)', verbose_name='dagen op voorhand bestellen'),
        ),
    ]
