# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-07 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0028_preorderdays_default0'),
        ('lunch', '0028_store_cash_enabled'),
    ]

    operations = [
    ]
